CREATE TABLE `sensingdatas` (
  `sensingId` INT NOT NULL AUTO_INCREMENT,
  `sensingdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `gas` FLOAT DEFAULT NULL,
  `humidity` FLOAT DEFAULT NULL,  
  `temp` FLOAT DEFAULT NULL,
  `tdsValue` FLOAT DEFAULT NULL,
  `water_temp` FLOAT DEFAULT NULL,
  `ph` FLOAT DEFAULT NULL,
  PRIMARY KEY (`sensingId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;